language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8
          dist: focal
          sudo: true

# GitHub branch
branches:
  only:
    - master

# install package and dependencies
install:
  - pip install scipy astropy
  - pip install coverage nose pytest==5.4.3 pytest-cov pytest-pep8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install sphinx sphinx-rtd-theme numpydoc travis-sphinx coveralls; fi

# run unit tests
script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then sphinx-apidoc -feo docs/source lenspack/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then travis-sphinx -v -o docs/build build -n -s docs/source; fi

# run coverage tests
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then travis-sphinx -o docs/build deploy; fi

# notification settings
notification:
  email: false
